### ISSUE TITLE
Failed to connect to the wayland display '(default)'

### ISSUE THREAD

**Issue by JVTEAM** [google-coral/project-birdfeeder#1] opened 2019-07-26 17:10 UTC
Not sure if this is working.  Ran the code and its stuck with this message.

        
error: XDG_RUNTIME_DIR not set in the environment.
Warning: gst-resource-error-quark: Could not initialise Wayland output (7): gstwaylandsink.c(333): gst_wayland_sink_find_display (): /GstPipeline:pipeline0/GstWaylandSink:waylandsink0:
Failed to create GstWlDisplay: 'Failed to connect to the wayland display '(default)''

**Comment by madurasenadeera** [comment] 2019-12-10 10:38
I am running into the same error. Were you able to solve the issue?

**Comment by Desertgeek** [comment] 2020-02-04 23:41
When running birdfeeder.sh with Coral camera on the Dev Board, I get:
** (python3:3933): CRITICAL **: 16:37:50.961: Failed to flush Wayland connection
thousands of lines in the Terminal window. 
I'm getting a results.log file which includes some confirmed bird IDs and images saved. But hundreds of images are being saved in just a few seconds of running before I ^Z out. I don't think this is the way is should run.

**Comment by Desertgeek** [comment] 2020-02-26 20:13
I found that there were two issues contributing to the behavior I described:

FIRST - I am running the birdfeeder.sh script in a terminal window on Mac OSX with USB-c to my laptop plugged into the OTG port on the Dev board. The Waylandsink is the end of the gstream pipeline that is processing the images from the camera and sending them to the tflite software for inferencing. Apparently, the Waylandsink object doesn't clear(flush) properly unless there is a HDMI monitor connected to the Coral Dev Board. I do not know why but if I plug a monitor into the HDMI port on the board, I see the camera image on the monitor and there is NO steady stream of error messages complaining that the sink us not flushing. Of course, the images do not show up on the terminal window.

SECOND - In the birdfeeder.sh script, there is a line 

“	—training False”

which is supposed to allow the collections of images to retrain the model if desired. I (mistakenly) thought that setting this parameter to “False” would cause the program to run in “classification” mode and not collect an image if only background was seen by the camera. But I was betting hundreds of images of the background. A study of the code showed that that would only happen if the program was running in training mode. It turns out that setting the —training parameter to False is not sufficient; it must be deleted from the parameter list in the birdfeeder.sh file. In classification mode, an image is saved only when a bird is “seen” by the camera in which case the event is recorded in the results.log file. This is the way I expect the program to run.

**Comment by y9luiz** [comment] 2020-03-05 14:48
try do:
sudo apt-get install gstreamer1.0-x
this solved for me.

**Comment by Desertgeek** [comment] 2020-03-05 20:24
On Mar 5, 2020, at 6:48 AM, Luiz Felipe <notifications@github.com<mailto:notifications@github.com>> wrote:

sudo apt-get install gstreamer1.0-x

Hello Luiz.

I tried your suggestion. Here is a bit of the result:

mendel@jumping-quill:~$ sudo apt-get install gstreamer1.0-x
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  gstreamer1.0-x
0 upgraded, 1 newly installed, 0 to remove and 51 not upgraded.
Need to get 1,247 kB of archives.
After this operation, 1,448 kB of additional disk space will be used.
Get:1 https://packages.cloud.google.com/apt mendel-bsp-enterprise-day/main arm64 gstreamer1.0-x arm64 1.14.4+imx-5 [1,247 kB]
Fetched 1,247 kB in 1s (1,145 kB/s)
Selecting previously unselected package gstreamer1.0-x:arm64.
(Reading database ... 49751 files and directories currently installed.)
Preparing to unpack .../gstreamer1.0-x_1.14.4+imx-5_arm64.deb ...
Unpacking gstreamer1.0-x:arm64 (1.14.4+imx-5) ...
Setting up gstreamer1.0-x:arm64 (1.14.4+imx-5) ...
mendel@jumping-quill:~$
mendel@jumping-quill:~$
mendel@jumping-quill:~$ echo now try runing the program
now try runing the program
mendel@jumping-quill:~$
mendel@jumping-quill:~$ sh birdfeeder/birdfeeder.sh
Loading /home/mendel/birdfeeder/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite with /home/mendel/birdfeeder/inat_bird_labels.txt labels.
Detected EdgeTPU dev board.
Gstreamer pipeline:  v4l2src device=/dev/video0 ! video/x-raw,format=YUY2,width=640,height=480,framerate=30/1 ! queue max-size-buffers=1 leaky=downstream  ! tee name=t
            t. ! queue max-size-buffers=1 leaky=downstream ! glupload ! glfilterbin filter=glcolorscale
               ! video/x-raw,format=RGBA,width=320,height=180 ! videoconvert ! video/x-raw,format=RGB,width=320,height=180 ! appsink name=appsink sync=false emit-signals=true max-buffers=1 drop=true
            t. ! queue max-size-buffers=1 leaky=downstream ! glupload ! glfilterbin filter=glcolorscale
               ! rsvgoverlay name=overlay ! waylandsink



** (python3:4481): CRITICAL **: 12:20:26.635: Failed to flush Wayland connection


** (python3:4481): CRITICAL **: 12:20:26.635: Failed to flush Wayland connection


** (python3:4481): CRITICAL **: 12:20:26.635: Failed to flush Wayland connection

The errors keep coming until I ^Z out of the program…

Steve Miller

**Comment by JVTEAM** [comment] 2020-03-05 21:12
I sold the dev board.  Mendel is just very unstable when you could just use the USB accelerator and get 90% of the functionality while being able to use raspbian.

**Comment by hjonnala** [comment] 2021-10-18 14:56
Please try with the latest code and feel free to reopen if issue still persists.

**Closed as completed by hjonnala** 2021-10-18 14:56 UTC
Labels: type:support
